
alg = input("Escreva Algo na tela: ")
print(type(alg))

print('É um char Alfanumerico? ')
print(alg.isalnum())
print('É um char Alfabetico? ')
print(alg.isalpha())
print('Fax parte da tabela ASCII? ')
print(alg.isascii())
print('É um digito? ')
print(alg.isdigit())
print('É Lowercase? ')
print(alg.islower())
print('É um numero decimal? ')
print(alg.isdecimal())
print('É identificavel? ')
print(alg.isidentifier())
print('É um numero? ')
print(alg.isnumeric())
print('Esta em UPPERCASE? ')
print(alg.isupper())
